package com.user.cardapp

enum class CardValidationEnum {
    ALL_INPUT_VALID,
    ENTER_CARD_HOLDER_NAME,
    ENTER_VALID_CARD_HOLDER_NAME,
    ENTER_CARD_NUMBER,
    ENTER_VALID_CARD_NUMBER,
    ENTER_EXPIRY_DATE,
    ENTER_VALID_EXPIRY_DATE,
    ENTER_CVV_NUMBER,
    ENTER_VALID_CVV_NUMBER,
    ENTER_ZIP_CODE,
    ENTER_VALID_ZIP_CODE,
    ENTER_NICK_NAME,
    ENTER_VALID_NICK_NAME,
    EMPTY
}